project_id = "ahrzjgkjlhixqubmpoya"

[functions.create-seller]
verify_jwt = true

[functions.cleanup-trash]
verify_jwt = true

[functions.crypto]
verify_jwt = true

[functions.change-seller-password]
verify_jwt = true

[functions.generate-temp-password]
verify_jwt = true

[functions.backup-data]
verify_jwt = true

[functions.restore-data]
verify_jwt = true

[functions.send-push-notifications]
verify_jwt = false

[functions.check-login-attempt]
verify_jwt = false
